package ru.ttb220.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF735C0C)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFE08B)
private val onPrimaryContainerLight = Color(0xFF584400)
private val secondaryLight = Color(0xFF0E6B58)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFA2F2DA)
private val onSecondaryContainerLight = Color(0xFF005141)
private val tertiaryLight = Color(0xFF8F4C34)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDBCF)
private val onTertiaryContainerLight = Color(0xFF72351F)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F1)
private val onBackgroundLight = Color(0xFF1F1B13)
private val surfaceLight = Color(0xFFFFF8F1)
private val onSurfaceLight = Color(0xFF1F1B13)
private val surfaceVariantLight = Color(0xFFEBE1CF)
private val onSurfaceVariantLight = Color(0xFF4C4639)
private val outlineLight = Color(0xFF7E7667)
private val outlineVariantLight = Color(0xFFCFC5B4)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF343027)
private val inverseOnSurfaceLight = Color(0xFFF8F0E2)
private val inversePrimaryLight = Color(0xFFE3C46D)
private val surfaceDimLight = Color(0xFFE1D9CC)
private val surfaceBrightLight = Color(0xFFFFF8F1)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFBF3E5)
private val surfaceContainerLight = Color(0xFFF5EDDF)
private val surfaceContainerHighLight = Color(0xFFF0E7D9)
private val surfaceContainerHighestLight = Color(0xFFEAE1D4)

private val primaryLightMediumContrast = Color(0xFF443400)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF836A1C)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF003E32)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF267A66)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF5D2510)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFFA05A41)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF8F1)
private val onBackgroundLightMediumContrast = Color(0xFF1F1B13)
private val surfaceLightMediumContrast = Color(0xFFFFF8F1)
private val onSurfaceLightMediumContrast = Color(0xFF141109)
private val surfaceVariantLightMediumContrast = Color(0xFFEBE1CF)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3B3629)
private val outlineLightMediumContrast = Color(0xFF585244)
private val outlineVariantLightMediumContrast = Color(0xFF736C5D)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF343027)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF8F0E2)
private val inversePrimaryLightMediumContrast = Color(0xFFE3C46D)
private val surfaceDimLightMediumContrast = Color(0xFFCDC6B9)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F1)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFBF3E5)
private val surfaceContainerLightMediumContrast = Color(0xFFF0E7D9)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE4DCCE)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFD9D1C3)

private val primaryLightHighContrast = Color(0xFF382A00)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF5A4700)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF003328)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF005343)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF501C07)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF753821)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF8F1)
private val onBackgroundLightHighContrast = Color(0xFF1F1B13)
private val surfaceLightHighContrast = Color(0xFFFFF8F1)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFEBE1CF)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF312C20)
private val outlineVariantLightHighContrast = Color(0xFF4E493B)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF343027)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFE3C46D)
private val surfaceDimLightHighContrast = Color(0xFFBFB8AB)
private val surfaceBrightLightHighContrast = Color(0xFFFFF8F1)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF8F0E2)
private val surfaceContainerLightHighContrast = Color(0xFFEAE1D4)
private val surfaceContainerHighLightHighContrast = Color(0xFFDBD3C6)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCDC6B9)

private val primaryDark = Color(0xFFE3C46D)
private val onPrimaryDark = Color(0xFF3D2F00)
private val primaryContainerDark = Color(0xFF584400)
private val onPrimaryContainerDark = Color(0xFFFFE08B)
private val secondaryDark = Color(0xFF86D6BE)
private val onSecondaryDark = Color(0xFF00382C)
private val secondaryContainerDark = Color(0xFF005141)
private val onSecondaryContainerDark = Color(0xFFA2F2DA)
private val tertiaryDark = Color(0xFFFFB59B)
private val onTertiaryDark = Color(0xFF55200B)
private val tertiaryContainerDark = Color(0xFF72351F)
private val onTertiaryContainerDark = Color(0xFFFFDBCF)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF16130B)
private val onBackgroundDark = Color(0xFFEAE1D4)
private val surfaceDark = Color(0xFF16130B)
private val onSurfaceDark = Color(0xFFEAE1D4)
private val surfaceVariantDark = Color(0xFF4C4639)
private val onSurfaceVariantDark = Color(0xFFCFC5B4)
private val outlineDark = Color(0xFF989080)
private val outlineVariantDark = Color(0xFF4C4639)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEAE1D4)
private val inverseOnSurfaceDark = Color(0xFF343027)
private val inversePrimaryDark = Color(0xFF735C0C)
private val surfaceDimDark = Color(0xFF16130B)
private val surfaceBrightDark = Color(0xFF3D392F)
private val surfaceContainerLowestDark = Color(0xFF110E07)
private val surfaceContainerLowDark = Color(0xFF1F1B13)
private val surfaceContainerDark = Color(0xFF231F17)
private val surfaceContainerHighDark = Color(0xFF2D2A21)
private val surfaceContainerHighestDark = Color(0xFF38342B)

private val primaryDarkMediumContrast = Color(0xFFFAD980)
private val onPrimaryDarkMediumContrast = Color(0xFF302400)
private val primaryContainerDarkMediumContrast = Color(0xFFA98E3D)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFF9CECD3)
private val onSecondaryDarkMediumContrast = Color(0xFF002C22)
private val secondaryContainerDarkMediumContrast = Color(0xFF4F9F89)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFFFD3C4)
private val onTertiaryDarkMediumContrast = Color(0xFF471503)
private val tertiaryContainerDarkMediumContrast = Color(0xFFCB7D61)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF16130B)
private val onBackgroundDarkMediumContrast = Color(0xFFEAE1D4)
private val surfaceDarkMediumContrast = Color(0xFF16130B)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF4C4639)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFE5DBC9)
private val outlineDarkMediumContrast = Color(0xFFBAB1A0)
private val outlineVariantDarkMediumContrast = Color(0xFF978F7F)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFEAE1D4)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
private val inversePrimaryDarkMediumContrast = Color(0xFF594600)
private val surfaceDimDarkMediumContrast = Color(0xFF16130B)
private val surfaceBrightDarkMediumContrast = Color(0xFF49443A)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A0703)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF211D15)
private val surfaceContainerDarkMediumContrast = Color(0xFF2B271F)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF363229)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF423D34)

private val primaryDarkHighContrast = Color(0xFFFFEFCA)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFDFC069)
private val onPrimaryContainerDarkHighContrast = Color(0xFF100A00)
private val secondaryDarkHighContrast = Color(0xFFB4FFE7)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFF82D2BA)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000E0A)
private val tertiaryDarkHighContrast = Color(0xFFFFECE6)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFFFAF94)
private val onTertiaryContainerDarkHighContrast = Color(0xFF1D0400)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF16130B)
private val onBackgroundDarkHighContrast = Color(0xFFEAE1D4)
private val surfaceDarkHighContrast = Color(0xFF16130B)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF4C4639)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFF9EFDC)
private val outlineVariantDarkHighContrast = Color(0xFFCBC2B0)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFEAE1D4)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF594600)
private val surfaceDimDarkHighContrast = Color(0xFF16130B)
private val surfaceBrightDarkHighContrast = Color(0xFF545045)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF231F17)
private val surfaceContainerDarkHighContrast = Color(0xFF343027)
private val surfaceContainerHighDarkHighContrast = Color(0xFF3F3B31)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF4B463C)


val GoldLightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val GoldDarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

val GoldMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

val GoldHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

val GoldMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

val GoldHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)
